[package]
authors = ["Iago"]
edition = "2018"
name = "parallelized-acotsp"
version = "0.1.0"
[dependencies]
indexmap = "1.0.2"
itertools = "0.7.11"
lazy_static = "*"
rand = "0.6.1"
rayon = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
