[package]
authors = ["Iago"]
edition = "2018"
name = "parallelized-acotsp"
version = "0.1.0"
[dependencies]
clap = "*"
indexmap = "1.0.2"
itertools = "^0.8"
lazy_static = "^1.2"
parking_lot = "*"
rand = "^0.6"
rayon = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
